spring:
  datasource:
    url: jdbc:postgresql://172.21.0.2:5432/sweetTaco
    username: zhelezyaka
    password: zh
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect